### ISSUE TITLE
채팅 목록 표시

### ISSUE THREAD

**Issue by sukjae** [connect-foundation/2019-20#125]
### 테스크 요약 

사용자가 진행중인 채팅방들에 대한 목록을 표시합니다

### 해당 테스크가 왜 필요한가요
 
Issue #77

현재 거래중이거나 과거에 거래한 상품에 대한 채팅 내용을 확인할 수 있습니다. 
이 화면을 통해 과거 채팅에 다시 접속할 수 있습니다.

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [ ] 채팅 목록 표시 UI
- [ ] 채팅 아이템 박스 UI (개별 채팅방 ex, 상대방 이름, 상품명, 최신 메세지 등)
- [ ] 화면 스크롤 

### 체크리스트

- [ ] 해당 이슈가 프로젝트의 목적과 부합되는가
- [ ] 테스크를 형식에 맞게 작성 하였는가
- [ ] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [ ] 해당하는 유저스토리를 참조 하였는가
- [ ] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [ ] 적절한 Projects에 추가 되었는가
- [ ] 모든 필수 항목을 작성하였는가
