### ISSUE TITLE
유저로서 물품의 구매를 위하여 상품조회가 가능하고, 판매를 위하여 제품의 등록 수정 삭제할 수 있다.

### ISSUE THREAD

**Issue by Johnie-Yeo** [connect-foundation/2019-20#23]
### 유저 스토리

유저로서 물품의 구매를 위하여 상품조회가 가능하고, 판매를 위하여 제품의 등록 수정 삭제할 수 있다.

### 상세한 설명

- 중고거래에 있어서 가장 핵심적인 기능으로써, 상품목록을 확인할 수 있는 수단이 필요합니다. 이에 일반적인 게시판 기능을 구현하되, 구매자에게 상품의 추가적인 정보를 제공합니다. 따라서, 상품 상태가 확인 가능한 이미지 저장소를 관리할 수 있는 기능을 구현하고, 부가적으로 상품 거래 상태, 제품의 상태, 가격정보등 물건 거래에 필요한 정보를 확인할 수 있어야 합니다.

- 데이터베이스는 마이크로 서비스 아키텍처를 따르기 위해 테이블을 별도로 분류하여 구현합니다. (ex: 상품테이블은 상품관리 서비스에만 존재, 유저 정보는 유저관리 서비스에만 존재, 추후 각각의 정보는 api를 통해 연동)

### 선행 이슈 (선택)
 

- 인증
  - 상품 수정, 삭제, 등록기능은 회원인 경우만 동작합니다. 우선순위에 따라 해당 기능은 목업으로 구현하고 추후 인증기능 구현시 연동합니다.

### 완료 조건

- [ ] 상품 테이블 설계
- [ ] Sequelize 설정
- [ ] 상품 이미지 업로드
- [ ] 상품 등록
- [ ] 상품 상세 조회
- [ ] 상품 삭제
- [ ] 상품 수정
- [ ] 상품 목록 조회
- [ ] 끌어올리기 기능 구현

### 체크리스트
- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] EPIC을 추가하였는가 (선택)
- [x] 유저 스토리를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 유저 스토리를 위한 충분한 완료 조건이 제시 되었는가
- [x] Assignees 를 추가 하였는가
- [x] 적절한 Labels 를 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가

**Comment by sukjae** [comment]
> 고생하셨습니다. 두가지 사항에 대해 comment를 남기며, 이 부분 내일 한번 회의를 해봤으면 합니다. 

## 라벨
일전에 `epic:상품관리`와 같이 라벨의 형태로 분류를 하기로 했던것으로 기억합니다. 이를 지켜주셔서 감사합니다. 

다만 드는 생각이, 이러한 방식으로 진행시 다시 쓰이지 않을 라벨 수가 너무 많아지지 않을까 걱정도 됩니다. 

## 유저스토리 -> 백로그
우리가 `유저 스토리`로 이슈를 만드니, 
프로젝트(백로그)에 하나의 큰 유저 스토리가 덩어리로 들어가서 시간과 우선순위 측정이 어려운것 같습니다. 

이 부분을 
1.  각각의 세부 테스크당 이슈로 쪼개거나, 
2.  프로젝트의 `노트` 를 추가하는 기능으로 테스크를 분류하는게 좋을 것 같습니다. 

### 1번의 방법으로 진행시,
- 작업별 우선순위를 지정할 수 있습니다
- 작업당 작업을 하는자(Assignees)를 지정하기 수월합니다.
- 이슈를 다는데 추가 시간이 소요됩니다. 

### 2번의 방법으로 진행시, 
- 작업별 우선순위를 지정할 수 있습니다
- 작업당 작업을 하는자(Assignees)를 지정하기 어렵습니다.
- 빠른 시간내에 추가할 수 있습니다. 

#### 첨부: project note 추가 기능
![image](https://user-images.githubusercontent.com/8156543/69051734-8e53c880-0a48-11ea-9b30-f02ea7fa1af5.png)
