### ISSUE TITLE
상품 이미지 업로드 설정

### ISSUE THREAD

**Issue by Johnie-Yeo** [connect-foundation/2019-20#28]
### 테스크 요약 

- 상품의 이미지를 전달받아 Object storage에 저장하고 사용자의 환경에 최적화된 이미지를 제공해주기 위한 작업입니다.

### 해당 테스크가 왜 필요한가요
 

- [유저로서 물품의 구매를 위하여 상품조회가 가능하고, 판매를 위하여 제품의 등록 수정 삭제할 수 있다.](https://github.com/connect-foundation/2019-20/issues/23)

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [ ] 상품 이미지 업로드
- [ ] 고화질/중화질/저화질 3단계로 나눠서 저장

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가

**Comment by Johnie-Yeo** [comment]
중복으로 이슈를 발행하였습니다 양해부탁드립니다.
