### ISSUE TITLE
나는 사용자로서 검색엔진의 도움을 받아서 검색어 입력에 도움을 받고 싶다.

### ISSUE THREAD

**Issue by kgpyo** [connect-foundation/2019-20#45]
### 유저 스토리

  나는 사용자로서 검색엔진의 도움을 받아서 검색어 입력에 도움을 받고 싶다.

### 상세한 설명

  중고나라, 당근마케에서 중고상품을 검색할 때 사용자의 실수로 인 한 오타, 유사어로 인한 동일 상품이지만 많은 목록을 보기 힘든 경우가 있습니다. 따라서 이러한 불편함을 해소하고자 엘라스틱 엔진을 사용하여 사용자 입력에 대한 오타를 보정하거나 관련된 상품을 제안받을 수 있게 합니다.

### 선행 이슈 (선택)
 
 
 - [#23 유저로서 물품의 구매를 위하여 상품조회가 가능하고, 판매를 위하여 제품의 등록 수정 삭제할 수 있다.](https://github.com/connect-foundation/2019-20/issues/23)

### 완료 조건

- [ ] 동의어/연관검색어 제시
- [ ] 검색기능
- [ ] 오탈자체크
- [ ] Elastic Search 환경설정
- [ ] MongoDB Transaction 제어

### 체크리스트
- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] EPIC을 추가하였는가 (선택)
- [x] 유저 스토리를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 유저 스토리를 위한 충분한 완료 조건이 제시 되었는가
- [x] Assignees 를 추가 하였는가
- [x] 적절한 Labels 를 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
