### ISSUE TITLE
추천검색어 제공

### ISSUE THREAD

**Issue by Johnie-Yeo** [connect-foundation/2019-20#46]
### 기능 요약

- 동의어/연관검색어 제시

### 기능 배경

- 상품을 검색하면 같은 상품이 다른 이름으로 등록되는 경우가 있습니다.
    (ex `IPhone === 아이폰 === iphone`)
- 상품검색시 다른 사용자가 어떤 검색어를 같이 검색했는지 연관 상품을 제시해 줌으로써 사용자의 선택의 폭을 넓혀줍니다.

### 원하는 결과

- 키워드로 검색시 동의어 목록 및 연관검색어를 추천검색어로 제시해 줍니다.

### 원하는 결과를 위한 방법 제시

- [ ] 네이버 혹은 구글 크롤링을 통해 동의어 및 연관검색어 정보 가져오기
- [ ] 키워드로 검색시 추천검색어 제공

### 체크리스트

- [x] 해당 이슈와 유사한 선행 이슈가 없는 것을 확인 하였는가
- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 이슈 제목은 직관적인가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 적절한 라벨을 추가하였는가
- [x] 모든 필수 항목을 작성하였는가
