### ISSUE TITLE
오탈자 보정

### ISSUE THREAD

**Issue by kgpyo** [connect-foundation/2019-20#48]
# 오탈자 보정

### 테스크 요약 

- 사용자가 '갤럯7'와 같이 특정 단어를 빼먹거나 '모지'와 같이 'ㅏ'를 'ㅣ'로 잘못 입력하는 경우 검색어가 없을 경우 검색어를 다시 수정하는 과정을 최소화하기 위해 특정한 경우 오탈자를 보정하여 검색결과를 제공합니다.

### 해당 테스크가 왜 필요한가요
 
- [사용자로서 검색엔진의 도움을 받아서 검색어 입력에 도움을 받을 수 있다.](https://github.com/connect-foundation/2019-20/issues/45)

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [ ] 어떤 경우에 오탈자를 보정하는가에 대한 결정
- [ ] 사용자가 자주 입력하는 오탈자와 정정 단어 데이터 수집

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
