### ISSUE TITLE
일래스틱 서치 환경설정

### ISSUE THREAD

**Issue by kgpyo** [connect-foundation/2019-20#49]
# 환경설정

### 테스크 요약 

- 일래스틱 서치를 적용하기 위해 데이터베이스와 연결하고, 데이터 동기화 방식을 결정합니다.

### 해당 테스크가 왜 필요한가요
 

- 일래스틱 서치를 해당 프로젝트에 이용할 수 있도록 설정합니다.
- 상품 수정/등록에 관련된 API 서버와 분리되어 있기 때문에 상품 정보를 조회할 수 있는 데이터베이스관리 방법을 결정해야 합니다. 데이터베이스 싱크를 유지하기 위해 풀링 방식을 사용하거나 중간서버를 두어서 푸시를 하는 방법등 여러가지가 있습니다. 각각의 장단점이 있으므로 해당 방법에 대해서 결정하고 이에 맞는 관련 설정을 적용합니다.

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [ ] 일래스틱과 데이터베이스 연결
- [ ] 데이터베이스 동기화
- [ ] 인덱스 설정

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
