### ISSUE TITLE
사용자로서 원하는 제약조건으로 필터링하여 원하는 조건의 상품들만 볼 수 있다.

### ISSUE THREAD

**Issue by kgpyo** [connect-foundation/2019-20#50]
# 필터

### 유저 스토리

- 사용자로서 원하는 제약조건으로 필터링하여 원하는 조건의 상품들만 볼 수 있다.

### 상세한 설명

- 사용자는 키워드 검색뿐만 아니라 내가 있는 지역, 가격범위, 카테고리, 현재 인기상품등의 조건으로 필터링 된 결과를 제공받을 수 있습니다. 이를 통해 내가 원하는 상품을 더욱 상세한 조건을 통해 검색할 수 있습니다.

### 선행 이슈 (선택)
 
 
 - [#23 유저로서 물품의 구매를 위하여 상품조회가 가능하고, 판매를 위하여 제품의 등록 수정 삭제할 수 있다.](https://github.com/connect-foundation/2019-20/issues/23)

### 완료 조건

- [ ] 지역기반 필터링
- [ ] 가격범위 필터링
- [ ] 카테고리 필터링
- [ ] 인기상품 필터링

### 체크리스트
- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] EPIC을 추가하였는가 (선택)
- [x] 유저 스토리를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 유저 스토리를 위한 충분한 완료 조건이 제시 되었는가
- [x] Assignees 를 추가 하였는가
- [x] 적절한 Labels 를 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가

**Comment by Johnie-Yeo** [comment]
유저스토리가 중복등록되었네요 close  하겠습니다.
