### ISSUE TITLE
상품 지역기반 검색

### ISSUE THREAD

**Issue by kgpyo** [connect-foundation/2019-20#51]
# 지역 기반 검색

### 테스크 요약 

지역 기반 검색을 이용하여 사용자가 원하는 지역에서의 거래글을 탐색할 수 있습니다. 

사용자는 한정된 지역 범위내에서의 상품에 대한 정보를 제공받을 수 있습니다.

### 해당 테스크가 왜 필요한가요
 

중고거래의 특성상, 신뢰의 문제로 인해 직거래를 선호하는 경향이 있습니다. 이런 상황에서 판매자는 자신의 직거래 판매 범위를 한정하고, 구매자는 자신이 직거래를 위하여 찾아갈 수 있는 범위를 지정함으로서 보다 더 맞춤화된 검색결과를 제공할 수 있습니다. 

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [ ] 일라스틱서치 혹은 몽고 DB선택
- [ ] 위에서 정한 DB연결
- [ ] 기능 구현
- [ ] API 제공

### 추가 설명 (선택)

일라스틱 서치의 [Geo queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-queries.html)를 사용해 볼 수 있습니다. 

또, mongoose에서 제공되는 좌표 기반 검색을 활용할 수 있습니다. [mongoose geojson](https://mongoosejs.com/docs/geojson.html)

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
