### ISSUE TITLE
상품 카테고리 필터링

### ISSUE THREAD

**Issue by Johnie-Yeo** [connect-foundation/2019-20#52]
### 테스크 요약 

- 사용자가 원하는 카테고리의 상품들만 제공해 줍니다.

### 해당 테스크가 왜 필요한가요
 

- [사용자로서 원하는 제약조건으로 필터링하여 원하는 조건의 상품들만 볼 수 있다](https://github.com/connect-foundation/2019-20/issues/47)
- 무분별하게 많은 정보가 아닌 사용자는 카테고리에 따른 상품 목록들만 제공 받을 수 있어야 합니다. 이를 통해 원하는 카테고리 내의 다양한 선택지를 제공 받을 수 있습니다.

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [ ] 카테고리에 따라 필터링된 목록을 제공

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
