### ISSUE TITLE
상품 검색시 가격 범위 제한 기능 제공

### ISSUE THREAD

**Issue by sukjae** [connect-foundation/2019-20#53]
### 테스크 요약 

구매자에게 구매 의사가 있는 범위를 한정하여 검색 결과를 받아볼 수 있는 기능을 제공합니다.

### 해당 테스크가 왜 필요한가요
 

중고거래의 특성상 물건의 판매가는 다양한 범위를 갖습니다. 이러한 상황에서 구매자는 적절한 판매가를 찾기위해 여러 상품을 둘러보며 구매 가능성이 희박한 상품들이 결과에 포함되곤 합니다. 이러한 불필요한 검색결과를 제거하고, 사용자에게 맞춤된 정보를 제공하기 위하여 필요합니다. 

참고 이슈 : #47

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [ ] 원하는 가격범위 검색 
- [ ] 최소 비교 가격 단위 선택(10원, 100원, 1000원 등)
- [ ] 비정상적인 가격범위 탐지 (ex: -1000원 ~ 1000원 또는 1000원 ~ 500원)

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
