### ISSUE TITLE
일래스틱 서치 검색

### ISSUE THREAD

**Issue by kgpyo** [connect-foundation/2019-20#55]
# 검색

### 테스크 요약 

- 구매자가 원하는 상품을 키워드를 통해 검색 시 해당하는 결과를 제공합니다.

### 해당 테스크가 왜 필요한가요
 

- [사용자로서 검색엔진의 도움을 받아서 검색어 입력에 도움을 받을 수 있다.](https://github.com/connect-foundation/2019-20/issues/45)
- 게시판으로서 기본기능으로서 키워드를 포함하는 항목을 검색할 수 있어야 합니다.

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [ ] Elastic Search를 이용하여 해당 인덱스의 값을 출력
- [ ] GUI를 통한 사용자로부터 검색어를 입력받고 실제 검색결과 출력

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
