### ISSUE TITLE
네이버 OAuth를 통한 회원 가입

### ISSUE THREAD

**Issue by Johnie-Yeo** [connect-foundation/2019-20#62]
### 테스크 요약 

네이버 OAuth를 통한 회원 가입

### 해당 테스크가 왜 필요한가요
 

[사용자로써 해당 사이트 이용을 위해서 회원가입 할 수 있다.](https://github.com/connect-foundation/2019-20/issues/61)

본 서비스를 이용하는데 있어 상품 등록 수정 삭제 및 채팅을 위해서는 인증과정이 필요합니다.
이에 우리는 사용자에게 직접적으로 ID 패스워드 등을 요구하지 않고 네이버의 resource server로 부터 필요한 필수 정보만 받아 오는 OAuth를 도입하기로 결정하였습니다.

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [x] passport-naver을 이용한 네이버 로그인 프로세스 구현
- [x] 기존의 UserDB에 없는 사용자일때 회원가입 프로세스 진행
- [x] 네이버로부터 필요한 정보를 받은 후 추가적인 정보(권한, zipcode) 요구
	- 권한은 특별한 코드를 입력하면 관리자로 회원가입이 가능한 조건을 추가
- [x] 필수 정보가 모두 입력되었을때 UserDB에 정보가 저장

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
