### ISSUE TITLE
구매자로서 판매자의 중고 상품을 구매하기 위해 대화를 시작할 수 있다

### ISSUE THREAD

**Issue by sukjae** [connect-foundation/2019-20#77]
### 유저 스토리

구매자로서 판매자의 중고 상품을 구매하기 위해 대화를 시작할 수 있다

### 상세한 설명

구매자의 입장에서 판매자가 올린 상품에 대해 문의/흥정 등을 진행하기 위해 개인적인 소통이 필요하기도 합니다. 댓글과 같이 다른 이에게도 노출될 수 있는 소통 채널 보다는 1:1로 private하기 위한 소통 공간이 필요합니다. 

### 완료 조건

**통신**
- [ ] 서버와의 소켓 연결
- [ ] 과거 메세지 불러오기
- [ ] 최신 메세지를 화면에 업데이트
- [ ] 채팅방 생성
- [ ] 채팅방 메세지 저장

**채팅 UI/UX**
- [ ] 사용자의 최신 메세지를 확인할 수 있도록 스크롤 조절
- [ ] 무한 스크롤
- [ ] 메세지 좌우 정렬을 통해 식별
- [ ] 메세지 작성 시간 노출
- [ ] 같은 날에 작성된 메세지 분류 (section)

**인증/권한**
- [ ] 허가된 사용자만 입장할 수 있는 로직

### 체크리스트
- [X] 해당 이슈가 프로젝트의 목적과 부합되는가
- [X] EPIC을 추가하였는가 (선택)
- [X] 유저 스토리를 형식에 맞게 작성 하였는가
- [X] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [X] 유저 스토리를 위한 충분한 완료 조건이 제시 되었는가
- [X] Assignees 를 추가 하였는가
- [X] 적절한 Labels 를 추가하였는가
- [X] 적절한 Projects에 추가 되었는가
- [X] 모든 필수 항목을 작성하였는가
