### ISSUE TITLE
채팅 UI/UX 

### ISSUE THREAD

**Issue by sukjae** [connect-foundation/2019-20#78]
### 테스크 요약 

구매자와 판매자간의 채팅을 원활하게 제공하기 위한 UI/UX 에 대한 내용을 포함합니다.

### 해당 테스크가 왜 필요한가요
 

Issue #77

적절한 UI/UX를 통하여 구매자와 판매자가 직관적으로 대화를 나누고, 그 과정에서 거래를 활발하게 진행할 수 있도록 장려합니다. 

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [x] 사용자의 최신 메세지를 확인할 수 있도록 스크롤 조절
- [x] 무한 스크롤
- [x] 메세지 좌우 정렬을 통해 식별
- [x] 메세지 작성 시간 노출
- [x] 같은 날에 작성된 메세지 분류 (section)

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
