### ISSUE TITLE
채팅 인증/권한

### ISSUE THREAD

**Issue by sukjae** [connect-foundation/2019-20#79]
### 테스크 요약 

대화에 참여하는 구매자와 판매자만이 입장할 수 있도록 로직을 작성합니다. 

### 해당 테스크가 왜 필요한가요
 

Issue #77

구매자와 판매자간의 1:1 채팅이므로, 이를 위해 허가된 사용자만 접근할 수 있어야 합니다. 이를 위해서 서버/클라이언트 모두 방어적인 로직이 필요합니다. 

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [ ] 허가된 사용자만 입장할 수 있는 로직

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
