### ISSUE TITLE
채팅 통신

### ISSUE THREAD

**Issue by sukjae** [connect-foundation/2019-20#80]
### 테스크 요약 

구매자와 판매자가 언제든 다시 찾아와 대화를 이어갈 수 있는 실시간 채팅 서비스를 제공합니다 .

### 해당 테스크가 왜 필요한가요
 

Issue #77

원격에서 구매자와 판매자가 대화를 하기 위해 통신이 필요 합니다.
또한, 대화 내용을 기록하고 추후에 다시 제공하기 위해 저장하는 방법이 필요합니다. 
마지막으로 이러한 통신과정에서의 메세지를 화면에 노출시킬 방법이 필요합니다. 

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [ ]  서버와의 소켓 연결
- [ ]  과거 메세지 불러오기
- [ ]  최신 메세지를 화면에 업데이트
- [ ]  채팅방 생성
- [ ]  채팅방 메세지 저장

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
