### ISSUE TITLE
유저정보 조회

### ISSUE THREAD

**Issue by kgpyo** [connect-foundation/2019-20#84]
### 테스크 요약 

- 사용자의 유저정보를 조회하는 기능입니다.

### 해당 테스크가 왜 필요한가요
 

- 사용자가 상품 찜하기, 판매, 구매 내역을 확인할 수 있어야 하고
- 위치정보를 수정할 수 있어야 하기 때문에 필요합니다.

### 해당 테스크를 위해 무엇을 어떻게 할건가요

- [ ] 상품 조회할 수 있는 페이지
- [ ] 위치 정보를 조정할 수 있는 페이지

### 체크리스트

- [x] 해당 이슈가 프로젝트의 목적과 부합되는가
- [x] 테스크를 형식에 맞게 작성 하였는가
- [x] 제 3자가 봤을 때 추가적인 질문 없이 이슈를 이해할 수 있는가
- [x] 해당하는 유저스토리를 참조 하였는가
- [x] 테스크에 해당하는 에픽과, 테스크 라벨을 추가하였는가
- [x] 적절한 Projects에 추가 되었는가
- [x] 모든 필수 항목을 작성하였는가
